### ISSUE TITLE
`comments` option should be set

### ISSUE THREAD

**Issue by cdepillabout** [raichoo/purescript-vim#11]
`comments` is not set, which makes commands like `gq` not work correctly.  

Here are the `comments` settings that other similar languages use:

haskell:
`setlocal comments=s1:{-,mb:-,ex:-},:--`

idris:
`setlocal comments=s1:{-,mb:-,ex:-},:\|\|\|,:--`

elm:
`setlocal comments=:--`

**Comment by arthur-xavier** [comment]
This is working now @cdepillabout. You can check it out if you update the plugin now :)

**Comment by cdepillabout** [comment]
Thanks!
