### ISSUE TITLE
Wrong highlighting after scrolling file

### ISSUE THREAD

**Issue by oblitum** [raichoo/purescript-vim#16]
Opening https://github.com/paf31/purescript-book/blob/master/chapter8/src/Main.purs and scrolling down twice with CTRL-d I get some strange highlighting related to strings, this behaviour doesn't seem very consistent. If then I move the cursor over the problematic lines, line by line, they get fixed.

[![asciicast](https://asciinema.org/a/ezsn4gpnx3w23fiy2jh0jmp8y.png)](https://asciinema.org/a/ezsn4gpnx3w23fiy2jh0jmp8y)

Reproduced both in Vim and NeoVim.

cc @arthur-xavier

**Comment by arthur-xavier** [comment]
Thanks for the report @oblitum. It seems I already got it fixed in the refactoring. I shall release it tomorrow or wednesday at latest. I'll add this file to the "test suite".

Thanks for the help! :)

**Comment by oblitum** [comment]
Looks like fixed, thanks!
