### ISSUE TITLE
new lines following line starting with `instance` are indented unnecessarily

### ISSUE THREAD

**Issue by michaelficarra** [raichoo/purescript-vim#2]
Due to this line: https://github.com/raichoo/purescript-vim/blob/68edbb413a131363da3444699dbc8804651501e2/indent/purescript.vim#L51

If I remove `,=in`, it is fixed, but that gets rid of indentation after lines ending with `in`.

**Comment by gavocanov** [comment]
I'm leaving one empty line before the instance declaration to cope with that, bit annoying but you get used to it. When done you can remove the empty line...
